name: 'Updates dependencies automatically'
description: 'Updates dependencies in code to latest semantic ver release. (e.g. TOOL_NAME_VERSION=0.9.17 in Dockerfile)'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN to get latest version with GitHub Release API'
    default: '${{ github.token }}'
  file:
    description: 'target file'
    required: true
  version_name:
    description: 'target version name. e.g. REVIEWDOG_VERSION'
    required: true
  repo:
    description: 'target GitHub repository. e.g. reviewdog/reviewdog'
    required: true
  tag:
    description: 'Check tags instead of releases.'
    default: 'false'
    required: false
  include:
    description: 'Regular expression to use only matched versions.'
    required: false
  exclude:
    description: 'Regular expression not to use matched versions.'
    required: false
outputs:
  current:
    description: 'current version'
  latest:
    description: 'latest version'
  repo:
    description: 'target GitHub repository. Same as the repo from input.'
runs:
  using: 'docker'
  image: 'Dockerfile'
# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'refresh-cw'
  color: 'orange'
